insert into colegios(nombre) values('El colegio del Olimpo');
insert into cursos(grado,salon,id_colegio) values (10,'A',1);
insert into cursos(grado,salon,id_colegio) values (10,'B',1);
insert into cursos(grado,salon,id_colegio) values (11,'A',1);
insert into cursos(grado,salon,id_colegio) values (11,'B',1);
insert into profesores (nombre) values ('Némesis');
insert into profesores (nombre) values ('Príapo');
insert into profesores (nombre) values ('Iris');
insert into asignaturas (nombre,id_curso,id_profesor) values('Matemáticas',1,1);
insert into asignaturas (nombre,id_curso,id_profesor) values('Matemáticas',2,1);
insert into asignaturas (nombre,id_curso,id_profesor) values('Matemáticas',3,1);
insert into asignaturas (nombre,id_curso,id_profesor) values('Matemáticas',4,1);
insert into asignaturas (nombre,id_curso,id_profesor) values('Español',1,2);
insert into asignaturas (nombre,id_curso,id_profesor) values('Español',2,2);
insert into asignaturas (nombre,id_curso,id_profesor) values('Ingles básico',1,3);
insert into asignaturas (nombre,id_curso,id_profesor) values('Ingles avanzado',2,3);
insert into asignaturas (nombre,id_curso,id_profesor) values('Pre Icfes',3,1);
insert into asignaturas (nombre,id_curso,id_profesor) values('Pre Icfes',4,1);
insert into estudiantes (nombre) values ('Afrodita');
insert into estudiantes (nombre) values ('Apolo');
insert into estudiantes (nombre) values ('Ares');
insert into estudiantes (nombre) values ('Artemisa');
insert into estudiantes (nombre) values ('Atenea');
insert into estudiantes (nombre) values ('Dionisio');
insert into estudiantes (nombre) values ('Hefesto');
insert into estudiantes (nombre) values ('Hera');
insert into estudiantes (nombre) values ('Hermes');
insert into estudiantes (nombre) values ('Hades');
insert into estudiantes (nombre) values ('Poseidón');
insert into estudiantes (nombre) values ('Zeus');
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (1,1);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (1,5);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (1,7);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (2,1);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (2,5);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (2,7);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (3,1);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (3,5);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (3,7);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (4,2);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (4,6);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (4,8);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (5,2);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (5,6);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (5,8);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (6,2);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (6,6);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (6,8);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (7,3);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (7,9);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (8,3);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (8,9);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (9,4);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (9,10);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (10,4);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (10,10);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (11,4);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (11,10);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (12,4);
insert into estudiantes_asignatura (id_estudiante,id_asignatura) values (12,10);
